version: "3.9"

services:
  server:
    build: ./server
    container_name: skill-test-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: skill-test-client
    restart: always
    ports:
      - "3000:80"
