name: Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SERVER_HOST }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/applications
            git clone https://github.com/${{ github.repository }}.git skill-test-client
            cd skill-test-client
            echo "${{ secrets.ENV }}" > .env
            sudo docker-compose down
            sudo docker system prune -f -a --volumes -f
            sudo docker-compose up --build -d
            cd ..
            rm -rf skill-test-client
